spring:
  datasource:
    url: jdbc:mysql://127.0.0.1/simple?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
    open-in-view: true
    hibernate:
      ddl-auto: create-drop
  devtools:
    livereload:
      enabled: true
    add-properties: true
    
server:
  port: 8085

logging:
  level:
    web: debug
    org:
      hibernate:
        SQL: debug
